spring:
  application:
    name: urssaAppPressing
  datasource:
    url: jdbc:postgresql://localhost:5432/urssa_pressing_v2
    username: ursa_admin
    password: Ursa2011.
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
api:
  prefix: api/v2

security:
  jwt:
    secret-key: 9232536c4450f0e4f03973d1d58df29dfca97b36a4eae7db16133db3aeb8a177
    expiration-time: 3600000
    refresh-token:
      expiration-time: 8000000000